name: account
description: A new Flutter project for software engineering.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  clipboard: ^0.1.3
  dotted_line: ^3.1.0
  path_provider: ^2.1.0
  share_plus: ^4.5.0
  animated_floating_buttons: ^0.0.2
  floating_action_bubble: ^1.1.4
  custom_refresh_indicator: ^2.0.1
  status_bar_control: ^3.2.1
  smooth_page_indicator: ^1.0.1
  move_to_background: ^1.0.2
  app_to_foreground: ^0.0.3
  screen_capture_event: ^1.1.1
  chips_choice: ^3.0.0
  audio_session: ^0.1.13
  flutter_overlay_window: ^0.4.3
  flutter_sound: ^9.2.13
  expandable: ^5.0.1
  crop_image: ^1.0.4
  loading_animation_widget: ^1.2.0+4
  syncfusion_flutter_datepicker: ^20.4.53
  lazy_load_indexed_stack: ^0.1.4
  syncfusion_flutter_datagrid: ^20.4.53
  syncfusion_flutter_datagrid_export: ^20.4.53-beta
  syncfusion_flutter_xlsio: ^20.4.53
  open_file: ^3.2.1
  dotted_border: ^2.0.0+3
  circular_menu: ^2.0.1
  get: ^4.6.5
  crop_your_image: ^0.7.5
  flutter_native_splash: ^2.2.19
  fluttertoast: ^8.1.2
  card_swiper: ^2.0.4
  mmkv: ^1.3.1
  photo_view: ^0.14.0
  flutter_screenutil: ^5.9.0
  dio: 5.0.0
  cookie_jar: ^3.0.1
  #  head_image_cropper: ^3.0.0
  badges: ^3.1.2
  sqflite: ^2.3.0
  dio_cookie_manager: ^2.0.0
  intro_slider: ^3.0.9
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  #  camera: ^0.10.2+1
  statusbarz: ^1.0.12
  flutter_keyboard_visibility: ^5.4.0
  animations: ^2.0.5
  fl_chart: ^0.60.0
  shimmer: ^2.0.0
  #  shimmer_animation: ^2.1.0+1
  #  fade_shimmer: ^2.0.1
  intl: ^0.17.0
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^20.4.44
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: FZQKBYSJW
      fonts:
        - asset: assets/fonts/FZQKBYSJW.TTF

  assets:
    - assets/images/back.png
    - assets/images/book0.png
    - assets/images/book1.png
    - assets/images/book2.png
    - assets/images/bottle.png
    - assets/images/bottom_item0.png
    - assets/images/bottom_item1.png
    - assets/images/bottom_item2.png
    - assets/images/budget_icon.png
    - assets/images/budget_top_icon.png
    - assets/images/change_book.png
    - assets/images/class_accommodation.png
    - assets/images/class_catering.png
    - assets/images/class_cloth.png
    - assets/images/class_communication.png
    - assets/images/class_daily.png
    - assets/images/class_decoration.png
    - assets/images/class_digital.png
    - assets/images/class_educate.png
    - assets/images/class_food.png
    - assets/images/class_mail.png
    - assets/images/class_medicine.png
    - assets/images/class_office.png
    - assets/images/class_other.png
    - assets/images/class_service.png
    - assets/images/class_transport.png
    - assets/images/class_usecar.png
    - assets/images/coin.json
    - assets/images/coin_dance.json
    - assets/images/cover_line.png
    - assets/images/export.png
    - assets/images/father.png
    - assets/images/filter.png
    - assets/images/grandfather.png
    - assets/images/guardian.png
    - assets/images/image_analyse.png
    - assets/images/intro0.png
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/intro3.png
    - assets/images/lock0.png
    - assets/images/lock1.png
    - assets/images/lock2.png
    - assets/images/lock3.png
    - assets/images/lock4.png
    - assets/images/lock5.png
    - assets/images/lock6.png
    - assets/images/logo.png
    - assets/images/mfifty.png
    - assets/images/mfive.png
    - assets/images/mhundred.png
    - assets/images/mode0.png
    - assets/images/mode00.png
    - assets/images/mode1.png
    - assets/images/mode11.png
    - assets/images/mone.png
    - assets/images/mother.png
    - assets/images/mten.png
    - assets/images/mtwenty.png
    - assets/images/p0.png
    - assets/images/person_bg0.png
    - assets/images/person_bg1.png
    - assets/images/person_bg2.png
    - assets/images/person_icon0.png
    - assets/images/person_icon1.png
    - assets/images/person_icon2.png
    - assets/images/search.png
    - assets/images/setting_icon0.png
    - assets/images/setting_icon1.png
    - assets/images/setting_icon2.png
    - assets/images/sound_bg.png
    - assets/images/summary_bg.png
    - assets/images/table_analyse.png
